sudo: required
services:
  - docker
language: node_js
cache:
  directories:
    - ~/.npm
    - "source/server/node_modules"
    - "source/client/node_modules"
node_js:
  - "8"
before_install:
  - rm -rf source/server/node_modules
  - rm -rf source/client/node_modules
install:
  - npm install -g lerna
  - npm install
script:
  - npm run test
  - npm run compile
