sudo: required
services:
  - docker
language: node_js
before_cache:
  - rm -f source/server/node_modules
  - rm -f source/client/node_modules
cache:
  directories:
    - ~/.npm
    - "source/server/node_modules"
    - "source/client/node_modules"
node_js:
  - "8"
install:
  - npm install -g lerna
  - npm install
script:
  - npm run test
  - npm run compile
