export const PASSWORD_SIMPLE_FETCH = "PASSWORD_SIMPLE_FETCH"
export const PASSWORD_SIMPLE_SUCCESS = "PASSWORD_SIMPLE_SUCCESS"

export const PASSWORD_ADVANCED_FETCH = "PASSWORD_ADVANCED_FETCH"
export const PASSWORD_ADVANCED_SUCCESS = "PASSWORD_ADVANCED_SUCCESS"

export const SETTINGS_UPDATE = "SETTINGS_UPDATE"
export const SETTINGS_VALIDATE = "SETTINGS_VALIDATE"
